### ISSUE TITLE
The list settings are cached; but it is not persisted.

### ISSUE THREAD

**Issue by RicardoRamirezR** [spatie/mailcoach-support#118]
Mailcoah: 2.1.1
Laravel: 7.3.0

When the list is created all goes smooth. Then I've tried to change, for example, the list name. It shows the change in the UI but the change is not persisted.

I dig in the code and have no clue of the solution, but if I do a `dd($request->all());` just at the beginning of the `EmailListSettingsController@update` it does not goes through it.

If I do:
![Captura de Pantalla 2020-03-25 a la(s) 12 38 16 p  m](https://user-images.githubusercontent.com/6526545/77568797-2f3f0e00-6e97-11ea-9769-b2882f7477e9.png)
I dumps the request input.

If I do a `php artisan cache:clear` it works as it should be.

**Comment by freekmurze** [comment]
We don't do any caching there, so that's not it.

I've just did a test on a few installations and it seems to be working fine. We also didn't get other reports of this problem. This makes me think that the problem is caused by something specific by your app. Are you using Mailcoach as a package?

Maybe it's validation failing, are you sure that all fields that you enter are valid?

**Comment by RicardoRamirezR** [comment]
@freekmurze I'm using as a package. I create a new Laravel 7 app then install the package and follow the docs.

I'll check if some validation is failing, but I do not have any validation errors.

**Comment by RicardoRamirezR** [comment]
@freekmurze yep, it was a validation error.

The validation error message is very small. It wouldn't be nice to show an alert?

The message is present in *Welcome mail* section, I set `Send customized welcome mail` and write only the subject.

If I set the subject but not the body Mailcoach will send the default welcome mail but with a personalized subject, which is that I want. I published the views then localized them to Spanish but the subject of `Confirmation mail` and `Welcome mail` was only in English. the *hack* on the database worked until I need to make other changes in the settings.

So, how to have custom subjects then?

**Comment by freekmurze** [comment]
We'll improve on this soon, probably by scrolling to the first error. @willemvb could you take a look at that?

I'm afraid I don't follow what you want to do with the welcome and/or confirmation mail. If the current options don't offer enough flexibly, you can create your own mailables and use those to send welcome and confirmation mails.

**Comment by RicardoRamirezR** [comment]
@freekmurze thanks!

When Send customized mail there are choices to send a default or customized mails.
* Default sends subject/body in English
* Customized you define subject *and* body

What I did in the database was:
* Set customized and set the subject

I publish the views and localize them.

The mails are sent with the custom subject and the localized body.

What I mean is that would be nice to have a custom subject.

**Comment by freekmurze** [comment]
@RicardoRamirezR I'm afraid you'll have to spell it out for me, as I still don't understand what you mean with "custom subject". In the UI we have custom subject fields.

<img width="713" alt="image" src="https://user-images.githubusercontent.com/483853/78541416-df950680-77f5-11ea-953a-a504a3f26804.png">

If it's an simple change, maybe it's to send me a diff of the changes you want.

**Comment by freekmurze** [comment]
Closing this due to inactivity and me not understanding the problem.

@RicardoRamirezR Since you have reported this issue, we have opened up the laravel-mailcoach repo. Maybe it's best that you just send us a PR with the change you'd like to see 👍
